apiVersion: v1
kind: Secret
metadata:
  name: {{ include "libretranslate.fullname" . }}-auth
type: Opaque
data:
  auth: {{ .Values.adminUser.auth | quote }}
  username: {{ .Values.adminUser.name | quote }}
  password: {{ .Values.adminUser.password | quote }}
